### PR TITLE
Fix responsive issues

### PR DESCRIPTION
**Pull request by veredrec**
Still have several issues to fix, but this addresses some of them:

- menu and logo in header are aligned center
- buttons for categories in modal take entire width
- images in footer are smaller
- menu items in header are smaller
- buttons take 2 rows in small device (**still need to fix spaces**)
- time setting title is bigger and tabs are smaller

### CODE REVIEW

**Comment by Heathercoraje** [comment]
modal-fix

**Comment by Heathercoraje** [comment]
This happens on mobile devices for both when timer is done and to ask one more time before clearing the entire record set.

**Comment by veredrec** [comment]
@Heathercoraje I was thinking of this PR as the first phase for making it responsive and there are still a list of things that are not responsive yet, but I think the majority is. I thought we can merge this one, and based on that finish the work on the responsiveness, including of course making the messages smaller (which I didn't even start to work on and it is of course on the list). What do you think?

**Comment by Heathercoraje** [comment]
@veredrec Of course I agree. I've started to make menus. so it would be good idea to merge this PR and then start from there, also you have weekend ahead.

**Pull request merged**
