### PR TITLE
Style - mobile responsive design

### PR DESCRIPTION
**Pull request by veredrec**
- Fixed messages' design from `sweet-alert` on mobile
- Changed `close` button in modal to take the entire width
- Made font in main  buttons a bit bigger in small devices

### CODE REVIEW

**Comment by veredrec** [comment]
It was very hard to change the messages height, but I did make them smaller in width and fixed the text in the buttons. I think it looks cute :) 
Let me know what you think!

**Comment by Heathercoraje** [comment]
It looks great! one last thing, the font inside list `.tableHead` (table heads) and `<td></td>` (list item) are tiny on mobile. Take a look and making them bigger on mobile would look nice. Other than this, all good hon! @veredrec

**Comment by veredrec** [comment]
@Heathercoraje I made the font size bigger with both media queries for `max-width: 500px` and `max-width: 450px`. I think it looks better now :)

**Comment by Heathercoraje** [comment]
Awesome!

**Pull request merged**
