### PR TITLE
Add image to readme with new idea of time blocks representation

### PR DESCRIPTION
**Pull request by veredrec**
- Add squares image to `img` folder
- Add image to `README` file

Relates #5

### CODE REVIEW

**Comment by Heathercoraje** [comment]
@veredrec  Do we want 5 or more options? I would suggest having a few (25/40/50 for example) options? thoughts?

**Comment by veredrec** [comment]
Yes, sure! I think 3 or 4 options would be great. The ones in the image are just an example. Do you want me to update the image so it has the 3 option you suggested? (If we offer 3 I would suggest 25, 45, 60)

**Comment by veredrec** [comment]
@Heathercoraje Should I merge it or do you want me to change the image?

**Comment by Heathercoraje** [comment]
@veredrec  updating the image would be great!

**Comment by veredrec** [comment]
I changed the image to the three options we've talked about.

**Comment by Heathercoraje** [comment]
merging! ❤️

**Pull request merged**
